---
title: "stl_lead_inequity.qmd"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---
.
```{r}
library(tidyverse)
library(janitor)
library(dplyr)

```

```{r}
stl_lead <- read.csv(here::here("data", "stl_blood_lead.csv"))

stl_lead <- janitor::clean_names(stl_lead)

names(stl_lead)
ncol(stl_lead)
dim(stl_lead)
data.class(stl_lead)
typeof(stl_lead)
summary(stl_lead)
```

```{r}
#we do this bc stl_lead was already a data frame
#mutate from "dplyr" which is a function
#mutate is for creating and deleting columns
stl_lead_prop <- data.frame(stl_lead) |> mutate(prop_white = white/total_pop)
```

```{r}
# Stl_lead_prop was called in from earlier bc we made into a function before by 
# by using the mutate function to add in a new column that was you can read it
#so thats why we didnt call in previous data
#ggplot isnt add data points till you add geom_point
#these are all labels
#labs is labels
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = prop_white)) +
  geom_point(color = "maroon", alpha = .5, size = 2) +
  theme_classic() +
  labs(title = "prop of white ppl with lead", x = "Percentage eleveted", y = "proportion of whites")
  
```

```{r}
ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)
```

```{r}
stl_lead_hist <- ggplot(data = stl_lead_prop, aes(x = pct_elevated))+
  geom_histogram( color = "orange", fill = "yellow")
```


